apiVersion:18
kind:18
metadata:18
  name:18
  labels:18
    app:18
spec:18
  replicas:18
  selector:18
    matchLabels:18
      app:18
  template:18
    metadata:18
      labels:18
        app:18
    spec:18
      containers:18
      - name:18
        image:18
        # Image will be automatically updated by CI/CD pipeline
        imagePullPolicy:18
        ports:18
        - containerPort:18
        resources:18
          limits:18
            cpu:18
            memory:18
          requests:18
            cpu:18
            memory:18
        livenessProbe:18
          httpGet:18
            path:18
            port:18
          initialDelaySeconds:18
          periodSeconds:18
        readinessProbe:18
          httpGet:18
            path:18
            port:18
          initialDelaySeconds:18
          periodSeconds:18
      imagePullSecrets:18
      - name:18